version: '3.1'
services:
  webpacker:
    build: .
    env_file:
      - '.env.docker'
    command: ./bin/webpack-dev-server
    volumes:
      - .:/webpacker-example-app
    ports:
      - '3035:3035'
  web:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    command: rails s -p 3000 -b 0.0.0.0
    image: colinxfleming/dcaf_case_management:latest
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      mongohost: db
    env_file:
      - .docker/web-variables.env
  db:
    image: mongo
    ports:
      - "27017:27017"
